# Generated by Django 5.2.7 on 2025-10-27 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('py', 'python'), ('c', 'C++'), ('js', 'JavaScript')], max_length=15, verbose_name='курсы')),
                ('course_num', models.PositiveSmallIntegerField(default=1, verbose_name='номер потока')),
                ('start_date', models.DateField(verbose_name='начало курса')),
                ('end_date', models.DateField(verbose_name='конец курса')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('surname', models.CharField(max_length=30, verbose_name='фамилия')),
                ('age', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16)], verbose_name='возраст')),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10, verbose_name='пол')),
                ('active', models.BooleanField(verbose_name='активный')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='фото')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='slug')),
                ('course', models.ManyToManyField(blank=True, to='students.courses', verbose_name='курсы')),
            ],
            options={
                'verbose_name': 'студенты',
                'verbose_name_plural': 'студенты',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, verbose_name='оценка')),
                ('date', models.DateField(verbose_name='дата')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.courses', verbose_name='курсы')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='чья оценка')),
            ],
            options={
                'verbose_name': 'оценки',
                'verbose_name_plural': 'оценка',
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['surname'], name='students_st_surname_0e1b31_idx'),
        ),
    ]
